# Generated by Django 3.0.8 on 2020-07-15 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelrelation', '0002_auto_20200714_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to='modelrelation.Address'),
        ),
    ]
