# Generated by Django 3.0.8 on 2020-07-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelrelation', '0004_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='country',
            field=models.ManyToManyField(to='modelrelation.Country'),
        ),
    ]
