# Generated by Django 3.0.8 on 2020-07-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='middel_name',
            new_name='middle_name',
        ),
    ]
