# Generated by Django 3.0.8 on 2020-07-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelextra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
