# Generated by Django 3.0.8 on 2020-07-21 01:49

from django.db import migrations, models
import modelextra.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelextra', '0002_auto_20200720_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='age',
            field=models.IntegerField(validators=[modelextra.models.validate_my_age]),
        ),
    ]
